### ISSUE TITLE
Add trinkets/curios support

### ISSUE THREAD

**Issue by Rakambda** [RakambdaOrg/OverpoweredMending#104]
Add trinkets/curios support.

### Discussed in https://github.com/RakSrinaNa/OverpoweredMending/discussions/103

<div type='discussions-op-text'>

<sup>Originally posted by **Vixeliz** September  1, 2022</sup>
### Describe the feature

This may already be done but I couldn't find any info confirming it. I am using ElytraSlots with Trinkets. And I was wondering does this mod also take account items equipped in trinket slots? I think it would be a nice addition if it doesn't.</div>

**Comment by Rakambda** [comment]
@Vixeliz From what I understood, you seem to use the Forge side of the force.

I made some changes with (hopefully) support for Curios inventories.

If you can try it that'd be cool.
You'll find the mod inside a zip file in the artifacts section : https://github.com/RakSrinaNa/OverpoweredMending/actions/runs/2974773754

**Comment by Muvkina** [comment]
I actually do use fabric I can set up a forge instance if you would like me to try out the forge version. But I do indeed use fabric with trinkets.

**Comment by Rakambda** [comment]
No worries I'll do trinkets

**Comment by Muvkina** [comment]
> No worries I'll do trinkets

Awesome I still am setting up a minimal forge instance just to let you know if the curios implementation works.

**Comment by Muvkina** [comment]
https://mclo.gs/riOqxQa

So the forge version does appear to crash when collecting experience orbs so you are aware. This is just a minimal forge instance on latest recommended forge version and latest versions of curios, caelus, elytraslot, and overpowered mending from the github action. I uploaded the log if you would like to look at it.

**Comment by Rakambda** [comment]
That's what happens when not testing on my side 😆 
Should be fixed there: https://github.com/RakSrinaNa/OverpoweredMending/actions/runs/2974868977

For trinkets though maybe it'll be done over the weekend. My fabric/forge setup decided to give random IO errors 😞

**Comment by Muvkina** [comment]
> 

No worries! Thanks for working on it at all! I'll test in a minute to make sure curios works. Whenever you do get around to adding trinkets just ping me and i'll be happy to test.

**Comment by Muvkina** [comment]
I can confirm the curios version does now work.

**Comment by Rakambda** [comment]
@Vixeliz There should be Trinkets support (hopefully, I didn't test 😆 ) in this build: https://github.com/RakSrinaNa/OverpoweredMending/actions/runs/2980910440

**Comment by Muvkina** [comment]
Awesome i'll give it a try right now!

**Comment by Muvkina** [comment]
Seems to work! Thanks so much

**Comment by Rakambda** [comment]
👍 Will release it officially maybe at the end of the weekend. I don't know if you play to play with it until then but who know, maybe a bug can pop up during that time.

Thanks for testing !

**Comment by Muvkina** [comment]
I will add it to my modpack and see if any problems arise with more mods(i tested in a minimal environment) I'll update you if I find any issues in the larger modpack.

**Comment by RUTHINAS** [comment]
Great feature. Can we get a backport to 1.18.2, please?

**Comment by Rakambda** [comment]
Will do when I have time
