### ISSUE TITLE
Add trinkets/curios support (1.18.2)

### ISSUE THREAD

**Issue by Rakambda** [RakambdaOrg/OverpoweredMending#109]
### Describe the feature

Backport #104

**Comment by Rakambda** [comment]
@RUTHINAS
Would be great if you could test it. You'll find the mod in a zip file in the artifacts section : https://github.com/RakSrinaNa/OverpoweredMending/actions/runs/3122505965

**Comment by RUTHINAS** [comment]
Seems to work great. The mods I'm using don't have other trinkets with durability than capes, so I didn't test the functionality for every slot. However, capes worked without issue, whether they were in the inventory or in the cape trinket slot. I would expect other slots to operate in a similar fashion.

Thank you!
