### ISSUE TITLE
Overpowered Mending Not Working

### ISSUE THREAD

**Issue by JustAlaska** [RakambdaOrg/OverpoweredMending#257]
### Describe the bug

For some reason, when the mod was on, EXP gained would go nowhere. It wouldn't go into my EXP bar but it wouldn't mend any of my mending-enchanted equipment either. As soon as I took this specific mod off, exp started working normally again.

### Minecraft version

1.20.2

### Fabric API version

0.90.0

### Mod version

1.20.2

**Comment by Rakambda** [comment]
I can't reproduce. Can you do it with OverpoweredMending alone?
There may be other mods that brings incompatibility.
