### ISSUE TITLE
Trinkets compat not working

### ISSUE THREAD

**Issue by pajicadvance** [RakambdaOrg/OverpoweredMending#325]
### Describe the bug

Noticed in the latest version of the mod for Fabric that items in trinket slots are not being repaired. Looking into it, it seems like the inventory provider method for it is commented out for some reason:

https://github.com/RakambdaOrg/OverpoweredMending/blob/minecraft/1.21.0/fabric/src/main/java/fr/rakambda/overpoweredmending/fabric/inventory/TrinketsInventoryProvider.java

Is there a reason that compat was disabled, or was it accidental?

### Minecraft version

1.21

### Fabric API version

0.102.0

### Mod version

1.21.0.1

**Comment by Rakambda** [comment]
The mod for that MC version was not available when I ported FallingTree. Will take a look at it again.
