### ISSUE TITLE
XP gain isn't 1:1 to XP orbs

### ISSUE THREAD

**Issue by parzivail** [RakambdaOrg/OverpoweredMending#5]
**Describe the bug**
XP gain is modified from the amount that you would receive from vanilla orbs. This isn't an issue per se but it breaks compatibility with any mod that allows XP storage and retrieval, like Kibe. I initially posted an [issue over there](https://github.com/lucaargolo/kibe/issues/51) but it turns out OM was the source of the issue.

**To Reproduce**
1. Install a mod that allows XP storage and retrieval
2. Gain a known amount of XP, say one level and zero points
3. Drain that XP into a tank, or similar
4. Retrieve the XP and note the discrepancy between the input amount and output amount

**Infos:**
 - Minecraft verson: 1.16.5
 - Fabric Loader: 0.11.1
 - Mod version: 2.2.2

**Comment by Rakambda** [comment]
Can you try with that version to see if it fixes the issue: https://www.dropbox.com/s/difz2304a085kn2/OverpoweredMending-Fabric-1.16.5-2.2.2.jar?dl=0

**Comment by parzivail** [comment]
Yep, looks like that patch works perfectly. Thanks!
